/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SessionExpiredImport } from './routes/session-expired'
import { Route as RequestAccessImport } from './routes/request-access'
import { Route as OidcCallbackImport } from './routes/oidc-callback'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as IndexImport } from './routes/index'
import { Route as AuthenticatedMapImport } from './routes/_authenticated/map'
import { Route as AuthenticatedApplicationUrlsImport } from './routes/_authenticated/application-urls'

// Create/Update Routes

const SessionExpiredRoute = SessionExpiredImport.update({
  path: '/session-expired',
  getParentRoute: () => rootRoute,
} as any)

const RequestAccessRoute = RequestAccessImport.update({
  path: '/request-access',
  getParentRoute: () => rootRoute,
} as any)

const OidcCallbackRoute = OidcCallbackImport.update({
  path: '/oidc-callback',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedMapRoute = AuthenticatedMapImport.update({
  path: '/map',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedApplicationUrlsRoute =
  AuthenticatedApplicationUrlsImport.update({
    path: '/application-urls',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/oidc-callback': {
      id: '/oidc-callback'
      path: '/oidc-callback'
      fullPath: '/oidc-callback'
      preLoaderRoute: typeof OidcCallbackImport
      parentRoute: typeof rootRoute
    }
    '/request-access': {
      id: '/request-access'
      path: '/request-access'
      fullPath: '/request-access'
      preLoaderRoute: typeof RequestAccessImport
      parentRoute: typeof rootRoute
    }
    '/session-expired': {
      id: '/session-expired'
      path: '/session-expired'
      fullPath: '/session-expired'
      preLoaderRoute: typeof SessionExpiredImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/application-urls': {
      id: '/_authenticated/application-urls'
      path: '/application-urls'
      fullPath: '/application-urls'
      preLoaderRoute: typeof AuthenticatedApplicationUrlsImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/map': {
      id: '/_authenticated/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AuthenticatedMapImport
      parentRoute: typeof AuthenticatedImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  AuthenticatedRoute: AuthenticatedRoute.addChildren({
    AuthenticatedApplicationUrlsRoute,
    AuthenticatedMapRoute,
  }),
  OidcCallbackRoute,
  RequestAccessRoute,
  SessionExpiredRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authenticated",
        "/oidc-callback",
        "/request-access",
        "/session-expired"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/application-urls",
        "/_authenticated/map"
      ]
    },
    "/oidc-callback": {
      "filePath": "oidc-callback.tsx"
    },
    "/request-access": {
      "filePath": "request-access.tsx"
    },
    "/session-expired": {
      "filePath": "session-expired.tsx"
    },
    "/_authenticated/application-urls": {
      "filePath": "_authenticated/application-urls.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/map": {
      "filePath": "_authenticated/map.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
