/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RequestAccessImport } from './routes/request-access'
import { Route as OidcCallbackImport } from './routes/oidc-callback'
import { Route as MapImport } from './routes/map'
import { Route as ApplicationUrlsImport } from './routes/application-urls'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const RequestAccessRoute = RequestAccessImport.update({
  path: '/request-access',
  getParentRoute: () => rootRoute,
} as any)

const OidcCallbackRoute = OidcCallbackImport.update({
  path: '/oidc-callback',
  getParentRoute: () => rootRoute,
} as any)

const MapRoute = MapImport.update({
  path: '/map',
  getParentRoute: () => rootRoute,
} as any)

const ApplicationUrlsRoute = ApplicationUrlsImport.update({
  path: '/application-urls',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/application-urls': {
      id: '/application-urls'
      path: '/application-urls'
      fullPath: '/application-urls'
      preLoaderRoute: typeof ApplicationUrlsImport
      parentRoute: typeof rootRoute
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapImport
      parentRoute: typeof rootRoute
    }
    '/oidc-callback': {
      id: '/oidc-callback'
      path: '/oidc-callback'
      fullPath: '/oidc-callback'
      preLoaderRoute: typeof OidcCallbackImport
      parentRoute: typeof rootRoute
    }
    '/request-access': {
      id: '/request-access'
      path: '/request-access'
      fullPath: '/request-access'
      preLoaderRoute: typeof RequestAccessImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  ApplicationUrlsRoute,
  MapRoute,
  OidcCallbackRoute,
  RequestAccessRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/application-urls",
        "/map",
        "/oidc-callback",
        "/request-access"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/application-urls": {
      "filePath": "application-urls.tsx"
    },
    "/map": {
      "filePath": "map.tsx"
    },
    "/oidc-callback": {
      "filePath": "oidc-callback.tsx"
    },
    "/request-access": {
      "filePath": "request-access.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
