apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: redis
      port: {{ .Values.service.port }}
      targetPort: redis
      protocol: TCP
  selector:
    app: {{ .Chart.Name }}
